version: '3.9'

services:
  tyc_app:
    image: tyc:1.3.0
    container_name: tyc_app
    environment:
      - mongodb=mongodb://tyc:mongo233@tyc_mongo:27017/tyc
      - action=csv
      - token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxOTEzNjM0MzEzNyIsImlhdCI6MTY4NDgyNTQ2MywiZXhwIjoxNjg3NDE3NDYzfQ.0HtNE0AI_7L7g7JYBLywDZ3awhfn7fhQ0uWBXVRuKUSLkKFWkMNxH5XJLxEzsw7AmdJTJ3zf6qIbFPqMT0bbAw
    volumes:
      - /path/txts:/app/txts
      - /path/logs:/app/logs
    depends_on:
      - mongodb
    networks:
      - default
  mongodb:
    image: mongo:4.4.19-rc2
    container_name: tyc_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: tyc
      MONGO_INITDB_ROOT_PASSWORD: mongo233
    volumes:
      - "/path/data:/data/db"
    networks:
      - default
